name: buddi
channels:
  - defaults
  - conda-forge
  - nvidia/label/cuda-11.8.0
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=2.3.1
  - alsa-lib=1.2.15.3
  - aom=3.13.2
  - attr=2.5.2
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.34.8
  - ca-certificates=2026.7.22
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - comm=0.2.3
  - cuda-cccl=11.8.89
  - cuda-command-line-tools=11.8.0
  - cuda-compiler=11.8.0
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cuobjdump=11.8.86
  - cuda-cupti=11.8.87
  - cuda-cuxxfilt=11.8.86
  - cuda-documentation=11.8.86
  - cuda-driver-dev=11.8.89
  - cuda-gdb=11.8.86
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-memcheck=11.8.86
  - cuda-nsight=11.8.86
  - cuda-nsight-compute=11.8.0
  - cuda-nvcc=11.8.89
  - cuda-nvdisasm=11.8.86
  - cuda-nvml-dev=11.8.86
  - cuda-nvprof=11.8.87
  - cuda-nvprune=11.8.86
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-nvvp=11.8.87
  - cuda-profiler-api=11.8.86
  - cuda-runtime=11.8.0
  - cuda-sanitizer-api=11.8.86
  - cuda-toolkit=11.8.0
  - cuda-tools=11.8.0
  - cuda-version=13.3
  - cuda-visual-tools=11.8.0
  - dataclasses=0.8
  - dav1d=1.5.3
  - dbus=1.16.2
  - debugpy=1.8.16
  - expat=2.8.2
  - ffmpeg=8.1.2
  - fftw=3.3.10
  - fontconfig=2.18.2
  - freetype=2.14.1
  - fribidi=1.0.16
  - fvcore=0.1.5.post20221221
  - gcc_impl_linux-64=11.4.0
  - gcc_linux-64=11.4.0
  - gdk-pixbuf=2.44.6
  - gds-tools=1.4.0.31
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - giflib=5.2.2
  - glib=2.86.3
  - glib-tools=2.86.3
  - glslang=15.3.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.15
  - grpcio=1.74.1
  - gstreamer-orc=0.4.42
  - gtest=1.17.0
  - gxx_impl_linux-64=11.4.0
  - gxx_linux-64=11.4.0
  - harfbuzz=12.3.0
  - icu=78.3
  - idna=3.11
  - importlib-metadata=8.7.0
  - intel-gmmlib=22.9.0
  - intel-media-driver=26.1.0
  - intel-openmp=2021.4.0
  - ipykernel=6.30.1
  - ipython=8.18.1
  - jack=1.9.22
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9f
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kernel-headers_linux-64=6.12.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.19
  - ld_impl_linux-64=2.40
  - leptonica=1.87.0
  - lerc=4.1.0
  - libabseil=20250512.1
  - libarchive=3.8.8
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libass=0.17.4
  - libcap=2.78
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcufile=1.18.1.6
  - libcufile-dev=1.4.0.31
  - libcurand=10.4.3.29
  - libcurand-dev=10.3.0.86
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.22
  - libdrm=2.4.134
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libexpat=2.8.2
  - libffi=3.4.8
  - libflac=1.5.0
  - libgcc=15.2.0
  - libgcc-devel_linux-64=11.4.0
  - libgcc-ng=15.2.0
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgl=1.7.0
  - libglib=2.86.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libgrpc=1.74.1
  - libiconv=1.18
  - libltdl=2.6.0
  - libnl=3.11.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnsl=2.0.0
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libogg=1.3.5
  - libopenjpeg=2.5.4
  - libopus=1.6.1
  - libpciaccess=0.18
  - libpng=1.6.56
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - librsvg=2.62.1
  - libsanitizer=11.4.0
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=11.4.0
  - libstdcxx-ng=15.2.0
  - libtheora=1.2.0
  - libtiff=4.7.1
  - libuuid=1.41.5
  - libva=2.23.0
  - libvorbis=1.3.7
  - libvpl=2.16.0
  - libvpx=1.16.0
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.3
  - libzlib=1.3.2
  - lz4-c=1.9.4
  - markdown=3.8.2
  - markupsafe=3.0.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.33.4
  - mpmath=1.3.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - nsight-compute=2022.3.0.22
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openssl=3.6.3
  - pango=1.56.4
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=26.0.1
  - pixman=0.46.4
  - portalocker=3.2.0
  - protobuf=6.31.1
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pulseaudio=17.0
  - pulseaudio-client=17.0
  - pulseaudio-daemon=17.0
  - pure_eval=0.2.3
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.9.25
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - pyzmq=27.0.2
  - rdma-core=61.0
  - re2=2025.11.05
  - readline=8.3
  - shaderc=2025.5
  - six=1.17.0
  - soxr=0.1.3
  - spirv-tools=2026.1
  - sqlite=3.53.2
  - stack_data=0.6.3
  - svt-av1=3.1.2
  - sympy=1.14.0
  - sysroot_linux-64=2.39
  - tabulate=0.9.0
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tensorboard=2.20.0
  - tensorboard-data-server=0.7.0
  - termcolor=3.1.0
  - tesseract=5.5.2
  - tk=8.6.15
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tornado=6.5.2
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - wayland=1.24.0
  - wayland-protocols=1.47
  - werkzeug=3.1.3
  - wheel=0.45.1
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-xorgproto=2024.1
  - xz=5.8.2
  - yacs=0.1.8
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.2
  - zstd=1.5.7
  - pip:
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - asttokens==3.0.2
      - beautifulsoup4==4.15.0
      - black==25.11.0
      - chumpy==0.70
      - click==8.1.8
      - cloudpickle==3.1.2
      - contourpy==1.3.0
      - crcmod==1.7
      - cryptography==49.0.0
      - cycler==0.12.1
      - cython==3.2.8
      - decorator==5.3.1
      - detectron2==0.6
      - einops==0.8.2
      - eval-type-backport==0.4.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - filelock==3.14.0
      - fonttools==4.60.2
      - freetype-py==2.5.1
      - fsspec==2025.10.0
      - gdown==5.2.2
      - gitdb==4.0.12
      - gitpython==3.1.54
      - h11==0.16.0
      - hf-xet==1.5.2
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.8.0
      - hydra-core==1.3.4
      - imageio==2.37.2
      - importlib-resources==6.5.2
      - iopath==0.1.9
      - ipdb==0.13.13
      - jmespath==0.10.0
      - json-tricks==3.17.3
      - kiwisolver==1.4.7
      - lap==0.5.13
      - lazy-loader==0.5
      - loguru==0.7.3
      - lxml==6.1.2
      - markdown-it-py==3.0.0
      - matplotlib==3.9.4
      - matplotlib-inline==0.2.2
      - mdurl==0.1.2
      - mmcv-full==1.7.2
      - mmpose==0.24.0
      - model-index==0.1.11
      - munkres==1.1.4
      - mypy-extensions==1.1.0
      - numpy==1.23.5
      - omegaconf==2.3.1
      - opencv-python==5.0.0.93
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.3
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.3.3
      - parso==0.8.7
      - pathspec==1.1.1
      - platformdirs==4.4.0
      - prompt-toolkit==3.0.52
      - pycocotools==2.0.11
      - pycryptodome==3.23.0
      - pydantic==2.13.4
      - pydantic-core==2.46.4
      - pyglet==2.1.15
      - pygments==2.20.0
      - pyopengl==3.1.0
      - pyparsing==3.3.2
      - pyrender==0.1.45
      - python-docx==1.2.0
      - pytokens==0.4.1
      - pytorch3d==0.7.8
      - pytz==2023.4
      - requests==2.28.2
      - rich==13.4.2
      - safetensors==0.7.0
      - scikit-image==0.24.0
      - scipy==1.13.1
      - sentry-sdk==2.66.1
      - setuptools==60.2.0
      - shellingham==1.5.4
      - simple-romp==1.1.3
      - smmap==5.0.3
      - smplx==0.1.28
      - soupsieve==2.8.4
      - tifffile==2024.8.30
      - timm==1.0.28
      - tomli==2.4.1
      - tqdm==4.65.2
      - traitlets==5.15.1
      - trimesh==4.12.2
      - typer==0.23.2
      - typing-inspection==0.4.2
      - tzdata==2026.3
      - urllib3==1.26.20
      - wandb==0.26.1
      - wcwidth==0.8.2
      - wget==3.2
      - xtcocotools==1.14.3
      - yapf==0.43.0
